### ISSUE TITLE
AttributeError: dataset (ICVL-Hand)

### ISSUE THREAD

**Issue by momo1986** [melonwan/denseReg#20]
When I run  python data/icvl.py:
it reports the error:

> Traceback (most recent call last):
>   File "data/icvl.py", line 271, in <module>
>     run_preprocess()
>   File "data/icvl.py", line 215, in run_preprocess
>     preprocess_op=dataset.preprocess_op(128, 128))
>   File "/fast/junyan/HandPose/denseReg/data/dataset_base.py", line 199, in get_batch_op
>     result = preprocess_op(dm, pose, self.cfg)
>   File "data/icvl.py", line 154, in preprocess_op
>     dm, pose, cfg = crop_from_xyz_pose(dm, pose, cfg, input_width, input_height)
>   File "/fast/junyan/HandPose/denseReg/data/preprocess.py", line 64, in crop_from_xyz_pose
>     if FLAGS.dataset == 'icvl':
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/flags.py", line 85, in __getattr__
>     return wrapped.__getattr__(name)
>   File "/root/anaconda3/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 472, in __getattr__
>     raise AttributeError(name)
> AttributeError: dataset

I create the soft link in the exp/data/icvl.
The icvl  data directory hierarchy looks like this:
**>Training
>>Depth(With many images in different directories）
>>labels.txt

>Testing
>>Depth(With many images in different directories）
>>labels.txt**

I am not sure how can I resolve this problem.

**Comment by twkx** [comment]
I have the exact same issue
